### ISSUE TITLE
对代码中的一个不解。

### ISSUE THREAD

**Issue by dowhilenet** [buginux/whats-new-in-swift-2#1]
```
 private(set) var books: Int = 0
```

因为刚开始学习Swift不知道在这里`private(set)`有和作用？

**Comment by buginux** [comment]
`private(set)` 说明只能在本文件内对这个变量进行修改。

**Comment by dowhilenet** [comment]
`private`本身不就限定了这个属性只能在这个类中了吗？和一个文件中有什么不同吗？

**Comment by buginux** [comment]
这句话的意思相当于只对 `set` 设置了 `private`，在别的文件是可以取得 `books` 的值的。

**Comment by dowhilenet** [comment]
嗯嗯，谢谢了。明白了！
